const defaultPlayers = [
    { id: 1, name: "Aarav Mehta", location: "Society Clubhouse", game: "Chess", level: "advanced", availability: "Weekend" },
    { id: 2, name: "Kabir Sharma", location: "Local Ground / Park", game: "Badminton", level: "intermediate", availability: "Evening" },
    { id: 3, name: "Rohan Patel", location: "Home Space", game: "Carrom", level: "beginner", availability: "Morning" }
];

if (!localStorage.getItem('players')) {
    localStorage.setItem('players', JSON.stringify(defaultPlayers));
}
if (!localStorage.getItem('requests')) {
    localStorage.setItem('requests', JSON.stringify([]));
}
/*Mobile based Navbar*/ 
let x = document.getElementById('menu');
let menuBtn = document.querySelector('.menuBtn');
let closeBtn = document.querySelector('.closeBtn');

function OpenMenu(){
    x.style.display = 'block';
    menuBtn.style.display = 'none';
    closeBtn.style.display = 'block';
}
function CloseMenu(){
    x.style.display = 'none';
    menuBtn.style.display = 'block';
    closeBtn.style.display = 'none';
}

function getCurrentUser() {
    return JSON.parse(localStorage.getItem('currentUser')) || null;
}

document.addEventListener("DOMContentLoaded", () => {
    const path = window.location.pathname;

    if (path.includes("register.html")) {
        initRegisterPage();
    } else if (path.includes("dashboard.html")) {
        initDashboardPage();
    } else if (path.includes("search.html")) {
        initSearchPage();
    } else if (path.includes("admin.html")) {
        initAdminPage();
    }
});



function initRegisterPage() {
    const form = document.getElementById('registerForm');
    if (!form) return;

    form.addEventListener('submit', (e) => {
        e.preventDefault();
        const user = {
            name: document.getElementById('name').value.trim(),
            location: document.getElementById('location').value,
            game: document.getElementById('game').value,
            level: document.getElementById('level').value,
            availability: document.getElementById('availability').value
        };
        localStorage.setItem('currentUser', JSON.stringify(user));
        
        let players = JSON.parse(localStorage.getItem('players')) || [];

        if (!players.some(p => p.name.toLowerCase() === user.name.toLowerCase())) {
            players.push({ id: Date.now(), ...user });
            localStorage.setItem('players', JSON.stringify(players));
        }

        alert("Profile Created Successfully!");
        window.location.href = "dashboard.html";
    });
}

function initDashboardPage() {
    const user = getCurrentUser();
    if (!user) {
        alert("Please set up a player profile first to access your dashboard.");
        window.location.href = "register.html";
        return;
    }

    document.getElementById('welcomeName').innerText = user.name;
    renderDashboardRequests();
}

function initSearchPage() {
    performSearch();

    const nameInput = document.getElementById('searchNameInput');
    const gameSelect = document.getElementById('searchGame');

    if (nameInput) nameInput.addEventListener('input', performSearch);
    if (gameSelect) gameSelect.addEventListener('change', performSearch);
}

function initAdminPage() {
    const players = JSON.parse(localStorage.getItem('players')) || [];
    const requests = JSON.parse(localStorage.getItem('requests')) || [];

    if (document.getElementById('statTotalUsers')) {
        document.getElementById('statTotalUsers').innerText = players.length;
    }
    if (document.getElementById('statActiveReqs')) {
        document.getElementById('statActiveReqs').innerText = requests.length;
    }
    if (document.getElementById('statSuccessRate')) {
        const successRate = requests.length > 0 ? Math.round((requests.filter(r => r.status === 'Confirmed').length / requests.length) * 100) : 0;
        document.getElementById('statSuccessRate').innerText = successRate + "%";
    }
}


function renderDashboardRequests() {
    const container = document.getElementById('requestsContainer');
    if (!container) return;
    
    const currentUser = getCurrentUser();
    const requests = JSON.parse(localStorage.getItem('requests')) || [];
    
    // Filter out requests targeting or generated by the logged-in individual
    const incomingRequests = requests.filter(req => req.receiverName === currentUser.name);
    const sentRequests = requests.filter(req => req.senderName === currentUser.name);

    if (incomingRequests.length === 0 && sentRequests.length === 0) {
        container.innerHTML = `
            <div class="card" style="grid-column: 1/-1; text-align: center; padding: 3rem;">
                <p style="color: var(--gray); font-size: 1.1rem;">No active match history or requests found. Head over to the partner discovery panel to get matching!</p>
            </div>`;
        return;
    }

    let htmlContent = '';

    if (incomingRequests.length > 0) {
        htmlContent += `<h3 style="grid-column: 1/-1; margin-top: 1rem; margin-bottom: 0.5rem; color: var(--dark); font-weight:700;">📩 Incoming Play Requests (Received)</h3>`;
        incomingRequests.forEach((req) => {
            const globalIndex = requests.findIndex(r => r === req);
            
            let borderAccent = 'var(--primary)';
            if (req.status === 'Confirmed') borderAccent = 'var(--secondary)';
            if (req.status === 'Rejected') borderAccent = '#ef4444';

            htmlContent += `
                <div class="card" style="border-left: 5px solid ${borderAccent}; display: flex; flex-direction: column; justify-content: space-between;">
                    <div>
                        <h4 style="margin-bottom: 0.5rem; color: var(--dark); font-weight:700;">From: ${req.senderName}</h4>
                        <p><strong>Game:</strong> ${req.game}</p>
                        <p><strong>Location:</strong> ${req.location}</p>
                        <p style="margin-top: 0.5rem;"><strong>Status:</strong> <span class="badge ${req.status === 'Confirmed' ? 'badge-beginner' : req.status === 'Rejected' ? 'badge-advanced' : 'badge-intermediate'}">${req.status}</span></p>
                    </div>
                    ${req.status === 'Pending' ? `
                        <div style="display: flex; gap: 0.5rem; margin-top: 1.5rem;">
                            <button class="btn btn-secondary" onclick="updateRequest(${globalIndex}, 'Confirmed')" style="padding: 0.5rem 1rem; font-size: 0.9rem; flex: 1;">Accept</button>
                            <button class="btn" onclick="updateRequest(${globalIndex}, 'Rejected')" style="background: #ef4444; color: var(--white); padding: 0.5rem 1rem; font-size: 0.9rem; flex: 1;">Reject</button>
                        </div>
                    ` : ''}
                </div>
            `;
        });
    }

    if (sentRequests.length > 0) {
        htmlContent += `<h3 style="grid-column: 1/-1; margin-top: 2rem; margin-bottom: 0.5rem; color: var(--dark); font-weight:700;">📤 Outbound Match Requests (Sent by You)</h3>`;
        sentRequests.forEach((req) => {
            let borderAccent = 'var(--primary)';
            if (req.status === 'Confirmed') borderAccent = 'var(--secondary)';
            if (req.status === 'Rejected') borderAccent = '#ef4444';

            htmlContent += `
                <div class="card" style="border-left: 5px solid ${borderAccent}; opacity: 0.95;">
                    <h4 style="margin-bottom: 0.5rem; color: var(--dark); font-weight:700;">Sent to: ${req.receiverName}</h4>
                    <p><strong>Game:</strong> ${req.game}</p>
                    <p><strong>Location:</strong> ${req.location}</p>
                    <p style="margin-top: 0.5rem;"><strong>Current Status:</strong> 
                        <span class="badge ${req.status === 'Confirmed' ? 'badge-beginner' : req.status === 'Rejected' ? 'badge-advanced' : 'badge-intermediate'}">${req.status}</span>
                    </p>
                    <p style="font-size: 0.85rem; color: var(--gray); margin-top: 0.5rem; font-style: italic;">
                        ${req.status === 'Pending' ? 'Waiting for their response...' : req.status === 'Confirmed' ? 'Match Confirmed! Setup your gear.' : 'Match Declined.'}
                    </p>
                </div>
            `;
        });
    }

    container.innerHTML = htmlContent;
}


window.updateRequest = function(index, newStatus) {
    let requests = JSON.parse(localStorage.getItem('requests')) || [];
    
    if (requests[index]) {
        requests[index].status = newStatus;
        if (newStatus === 'Rejected') {
            alert("Play request declined successfully.");
        } else {
            alert("Match confirmed! Grab your gear and get ready to play!");
        }
        localStorage.setItem('requests', JSON.stringify(requests));
        renderDashboardRequests();
    }
};


function performSearch() {
    const gameSelect = document.getElementById('searchGame');
    const nameInput = document.getElementById('searchNameInput');

    const gameFilter = gameSelect ? gameSelect.value : 'All';
    const nameFilter = nameInput ? nameInput.value.toLowerCase().trim() : '';
    
    const players = JSON.parse(localStorage.getItem('players')) || [];
    const resultsContainer = document.getElementById('searchResults');

    if (!resultsContainer) return;

    const filtered = players.filter(p => {
        const matchesGame = (gameFilter === 'All' || p.game.toLowerCase() === gameFilter.toLowerCase());
        const matchesName = p.name.toLowerCase().includes(nameFilter);
        return matchesGame && matchesName;
    });

    if (filtered.length === 0) {
        resultsContainer.innerHTML = `
            <div class="card" style="grid-column: 1 / -1; text-align: center; padding: 3rem;">
                <p style="color: var(--gray); font-size: 1.1rem;">No matching players found matching those criteria.</p>
            </div>`;
        return;
    }

    resultsContainer.innerHTML = filtered.map(p => `
        <div class="card">
            <h3 style="color: var(--dark); font-weight: 700; margin-bottom: 0.5rem;">${p.name}</h3>
            <p><strong>Preferred Game:</strong> ${p.game}</p>
            <p><strong>Preferred Location:</strong> ${p.location}</p>
            <p><strong>Availability:</strong> ${p.availability}</p>
            <p style="margin-top: 0.5rem;"><strong>Skill Metric:</strong> <span class="badge badge-${p.level}">${p.level.toUpperCase()}</span></p>
            <button class="btn btn-primary" onclick="sendPlayRequest('${p.name}', '${p.game}', '${p.location}')" style="margin-top: 1.5rem; width:100%; font-size: 0.95rem; padding: 0.6rem;">Send Play Request</button>
        </div>
    `).join('');
}

window.sendPlayRequest = function(targetName, game, location) {
    const currentUser = getCurrentUser();
    
    if (!currentUser) {
        alert("Please set up your profile first before sending match requests!");
        window.location.href = "register.html";
        return;
    }

    if (currentUser.name.toLowerCase() === targetName.toLowerCase()) {
        alert("You cannot send a play request to yourself!");
        return;
    }

    let requests = JSON.parse(localStorage.getItem('requests')) || [];
    

    const isDuplicate = requests.some(r => r.senderName === currentUser.name && r.receiverName === targetName && r.game === game && r.status === 'Pending');
    if (isDuplicate) {
        alert(`You already have a pending request out to ${targetName} for ${game}!`);
        return;
    }

    requests.push({
        senderName: currentUser.name,
        receiverName: targetName,
        game: game,
        location: location,
        status: 'Pending'
    });

    localStorage.setItem('requests', JSON.stringify(requests));
    alert(`Play Request successfully sent to ${targetName}!`);
};

// Clear History Button
window.clearRequestHistory = function() {
    const currentUser = getCurrentUser();
    if (!currentUser) return;

    let requests = JSON.parse(localStorage.getItem('requests')) || [];
    
    const userChoice = prompt(
        "What history details would you like to clear?\n\n" +
        "Type '1' to clear requests.\n" +
        "Type '2' to clear Incoming requests.\n" +
        "Type '3' to wipe ALL match requests entirely."
    );

    if (userChoice === '1') {
        requests = requests.filter(req => req.senderName !== currentUser.name);
        localStorage.setItem('requests', JSON.stringify(requests));
        alert("Your sent request history has been cleared.Thank You!");
    } else if (userChoice === '2') {
        requests = requests.filter(req => req.receiverName !== currentUser.name);
        localStorage.setItem('requests', JSON.stringify(requests));
        alert("Your received incoming request history has been cleared.Thank You!");
    } else if (userChoice === '3') {
        if (confirm("Are you completely sure you want to delete all incoming and outbound match logs? This cannot be undone.")) {
            localStorage.setItem('requests', JSON.stringify([]));
            alert("All global request logs have been reset.Thank You!");
        } else {
            return;
        }
    } else if (userChoice !== null) {
        alert("Invalid selection option. No changes were applied.");
        return;
    } else {
        return; // User canceled
    }

    renderDashboardRequests();
};